# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b94853d0c628ef9fec8ac655388c657a"
name = "Phox Data Consent"
application_url = "https://data-consent-phox-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "customers_email_marketing_consent/update" ]
  uri = "/webhooks/app/customers_email_marketing_consent_update"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks/app/customers_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/orders_create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_customers,write_products"

[auth]
redirect_urls = [
  "https://data-consent-production-6bb1.up.railway.app/api/auth"
]
